### ISSUE TITLE
Links to new site have a typo

### ISSUE THREAD

**Issue by PaulMEdwards** [Electric-Hive/waggle-dance-programming-guide#2]
The links in the repository description and readme pointing to the following location has a typo:
https://electric-hive.github.io/waggle-dance-programming-guide/

It should be (remove first hyphen):
https://electrichive.github.io/waggle-dance-programming-guide/

**Comment by opheron** [comment]
Thanks Paul! The Electric Hive group changed its URL, so I will update appropriately. :)
